### ISSUE TITLE
PHP syntax highlighting

### ISSUE THREAD

**Issue by pkill37** [mybb/docs.mybb.com#29]
PHP syntax highlighting only works if the code snippet starts with `<?php`.

e.g. https://mybb.github.io/18/developers/plugins/how-to/

**Comment by JordanMussi** [comment]
Doesn't using 

``````
```php
require_once MYBB_ROOT."/inc/adminfunctions_templates.php";
    find_replace_templatesets(
    "index",
    "#" . preg_quote('<body>') . "#i",
    '<body>{$myVar}'
);
```
``````

work?

``` php
require_once MYBB_ROOT."/inc/adminfunctions_templates.php";
    find_replace_templatesets(
    "index",
    "#" . preg_quote('<body>') . "#i",
    '<body>{$myVar}'
);
```

**Comment by pkill37** [comment]
Yeah, on GitHub, not on the site. See the link above.

**Comment by JordanMussi** [comment]
Issue on Jekyll tracker: jekyll/jekyll#1262
If we use the `{% highlight %}` tags then it'll work without opening and closing PHP tags...

**Comment by JoshHarmon** [comment]
Ok. Any docs with PHP in them either have to start with opening PHP tags, or you have to use {% highlight php startinline %}

I'm going to ignore the 1.6 Docs, since I consider those deprecated along with MyBB 1.6 itself. So within the 1.8 Docs, from what I can tell, this affects:
- [x] http://docs.mybb.com/1.8/merge/troubleshooting/
- [x] http://docs.mybb.com/1.8/faq/mail/
- [x] http://docs.mybb.com/1.8/development/standards/
- [x] http://docs.mybb.com/1.8/development/plugins/
- [x] http://docs.mybb.com/1.8/development/plugins/ajax/
- [x] http://docs.mybb.com/1.8/development/plugins/database-methods/
- [x] http://docs.mybb.com/1.8/development/plugins/templates/
- [x] http://docs.mybb.com/1.8/administration/security/recovery/

I'm going to start work on fixing the markup for those so that we can have pretty syntax highlighting. Pages look pretty boring without color mixed in.

**Comment by JoshHarmon** [comment]
Welp... Here goes nothing...

Edit: Since the last reference, earliest at top (forgot to tag the issue in the commits!)
a7768d4007068cc1e881e498aa1916704544c6b4
67fa75afd57018b5186678d744c128158c545377
11764ce7a1528056b67b3d862a6a1b2fdb845cf2
cb85a42f67e9a48312176f90ba969c66356eb604
9f2e640e30e2c9b85112df1e2449fda877aff5b5
7fdab44ce984a03bc02fcea47601a25414b2c97f
62679e6bf4c0a49328c6742be4c465e6cd1c526c
eed2b4398c7e7625d654be906f185d911864bdf3
b65b6813173973459026b758aad4e338d7ae57a0

**Comment by JoshHarmon** [comment]
Aaaand now it should build.

**Comment by JoshHarmon** [comment]
Think this is fixed now!

**Comment by pkill37** [comment]
Cool!

**Comment by JoshHarmon** [comment]
You're alive!? It's been a long time since we've heard/seen anything from you! :smile:
